# SPDX-License-Identifier: LGPL-3.0-or-later

insert_tube_tooltip = (
    "Create a pipe/tube not referenced to a single wire\n"
    "______________________________________________________________________________________________________________________________________ \n"
	"Usage \n"
	"Select an object to attach the pipe to that object \n"
	" • If the selected object has ports, it will insert the pipe at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the pipe at the highest numbered port. \n"
    " • If the selected object has no ports, the pipe will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the pipe if it is inserted backwards. \n"
    " • If no objects are selected, the pipe will be inserted at the origin aligned with the Z axis \n"
	"\n"
    "In the window, first select the pipe schedule, then select the nominal diameter.\n"
    "Enter the pipe length into the text box. If no length is entered, a 200 mm length will be assumed.\n"
    "Click 'Insert' to insert the pipe.\n"
    "Apply button:\n"
    "Modifies the selected pipe to apply the selected schedule, nominal diameter, and entered length"
    "\n"
    "Reverse button:\n"
    "Rotates the pipe 180 degrees about its base pivot point.\n"
    "\n"
	)
frameit_tooltip = (
    "Relocate existing & selected beam at Preselected edge\n"
    "_____________________________________________________ \n"
	"Usage \n"
    "Preselected the following:\n"
    "• Choose a existing beam at current document then select a edge target where beam will be relocated"
    "Press [ESC] to cancel relocation function"
)
framebranchmanager_tooltip = (
    "Create a framebranch object with beam nest on tree. this object create parametric frames allowing change base sketch, path or wire and adapt to new dimentions\n"
    "______________________________________________________________________________________________________________________________________ \n"
	"Usage \n"
    "Preselected the following:\n"
    "• Choose a existing sketch/path(s) then choose profile to be applied on pop up windows\n"
)
spinsect_tooltip = (
    "Spin beam object(s) selected around the Z axis of its wire/sketch shape  by 45 degrees each click\n"
    "______________________________________________________________________________________________________________________________________ \n"
	"Usage \n"
    "Preselected the following:\n"
    "• Select beam object(s) to spin\n"
)
reversebeam_tooltip = (
    "Spin beam object(s) selected around the X axis of its wire/sketch shape  by 180 degrees each click\n"
    "______________________________________________________________________________________________________________________________________ \n"
	"Usage \n"
    "Preselected the following:\n"
    "• Select beam object(s) to spin\n"
    "Note: - if one edge of the object is selected, that is used\n"
    "as the pivot of rotation."
)
shiftbeam_tooltip = (
    "Dialog to translate and copy objects.\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "• [x/y/z] textboxes: direct input of amount of translation in each direction"
    "• [Multiple] textbox: the multiple coefficient of the translation amount.\n"
    "• [Steps] textbox: the denominator of the translation amount. It's used when the amount of translation is to be covered in some steps.\n"
    "• [move/copy] radiobuttons: to select if the selected objects shall be copied or only translated.\n"
    "• [Displacement] button: takes the amount and direction of translation from the distance of selected entities (points, edges, faces).\n"
    "• [Vector] button: defines the amount and direction of translation by the orientation and length of the selected edge.\n"
    "• [OK] button: execute the translation\n"
    "• [Cancel]: exits\n"
)
levelbeam_tooltip = (
    "Tool to flush the parallel faces of two objects.\n"
    "_________________________________________________ \n"
	"Usage \n"
    "Preselected the following:\n"
    "1.- Select fisrt beam face to take as reference\n"
    "2.- Select second beam face to translate and match faces coplanar\n"
    "Note: - actually the command takes to the same level, respect the position and orientation \n of the first face selected, the center-of-mass of all faces selected. Thus it translates the objects even if the faces are not parallel.\n"
)
pivotbeam_tooltip = (
    "Tool to pivot & copy around one edge or principal X/Y/Z axis\n"
    "_________________________________________________ \n"
	"Usage \n"
    "Preselected the following:\n"
    "1.- Select fisrt beam to modify rotation angle or press 's' key\n"
    "2.- Choose a principal axis with x, y , z button or select a edge then press 'assign axis' button \n"
    "3.- Press 'x' key to execute rotation\n"
    "Note: - actually the command takes to the same level, respect the position and orientation \n of the first face selected, the center-of-mass of all faces selected. Thus it translates the objects even if the faces are not parallel.\n"
)
elbow_tooltip = (
    "Tool to insert an elbow fitting\n"
    "_________________________________________________ \n"
	"Usage \n"
	"Select an object to attach an elbow to that object \n"
	" • If the selected object has ports, it will insert the fitting at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the fitting at the highest numbered port. \n"
    " • If the selected object has no ports, the fitting will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the fitting if it is inserted backwards. \n"
    " • If no objects are selected, the fitting will be inserted at the origin aligned with the Z axis \n"
	"\n"
    "In the window, first select the pipe schedule (or pressure class for socket/threaded fittings), then select the nominal diameter.\n"
    "For butt welded elbows, a bend angle (degrees) and bend radius (length with units) may be entered, which will override the bend angle and bend radius from the fitting data file.\n"
    "For socket welded/threaded elbows, a bend angle may be inserted which will override the bend angle from the fitting data file"
    "Click 'Insert' to insert the fitting.\n"
    "After insertion, the rotation dial may be used to rotate the fitting about the insertion port axis to the desired orientation.\n"
    "Apply button:\n"
    "Modifies the selected fitting to apply the selected schedule, nominal diameter, and angle or bend radius"
    "\n"
    "Reverse button:\n"
    "Rotates the fitting 180 degrees about its attachment port.\n"
    "\n"
	)

reduct_tooltip = (
    "Tool to insert a concentric or eccentric pipe reducer\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select an object to attach the reducer to that object \n"
    " • If the selected object has ports, it will insert the reducer at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the reducer at the highest numbered port. \n"
    " • If the selected object has no ports, the reducer will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the reducer if it is inserted backwards. \n"
    " • If no objects are selected, the reducer will be inserted at the origin aligned with the Z axis \n"
    "\n"
    "In the window, first select the pipe schedule, then select the nominal diameter of the larger end from the upper list.\n"
    "Next, select the nominal diameter of the smaller end from the lower list.\n"
    "Use the 'Insert on Larger End' / 'Insert on Smaller End' radio buttons to choose which end attaches to the selected port.\n"
    "Check the 'Eccentric' checkbox to insert an eccentric reducer. When checked, a rotation dial appears to orient the flat side.\n"
    "Click 'Insert' to insert the reducer.\n"
    "If necessary, use the rotation dial to align the eccentric reducer in the desired orientation"
    "Apply button:\n"
    "Modifies the selected reducer(s) to apply the selected schedule, nominal diameters, and eccentric/concentric setting.\n"
    "\n"
    "Reverse button:\n"
    "Rotates the reducer 180 degrees about its attachment port.\n"
    "\n"
)

cap_tooltip = (
    "Tool to insert a pipe cap (butt-weld, socket-weld, or threaded)\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select an object to attach the cap to that object \n"
    " • If the selected object has ports, it will insert the cap at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the cap at the highest numbered port. \n"
    " • If the selected object has no ports, the cap will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the cap if it is inserted backwards. \n"
    " • If no objects are selected, the cap will be inserted at the origin aligned with the Z axis \n"
    "\n"
    "In the window, first select the pipe schedule (or pressure class for socket-weld/threaded caps), then select the nominal diameter.\n"
    "For butt-weld caps, the size list shows nominal diameter, outer diameter, and wall thickness.\n"
    "For socket-weld or threaded caps, the size list shows nominal diameter and outer diameter.\n"
    "Click 'Insert' to insert the cap.\n"
    "Apply button:\n"
    "Modifies the selected cap(s) to apply the selected schedule and nominal diameter.\n"
    "\n"
    "Reverse button:\n"
    "Rotates the cap 180 degrees about its base pivot point.\n"
    "\n"
)

tee_tooltip = (
    "Tool to insert a tee fitting (butt-weld, socket-weld, or threaded)\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select an object to attach the tee to that object \n"
    " • If the selected object has ports, it will insert the tee at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the tee at the highest numbered port. \n"
    " • If the selected object has no ports, the tee will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the tee if it is inserted backwards. \n"
    " • If no objects are selected, the tee will be inserted at the origin aligned with the Z axis \n"
    "\n"
    "In the window, first select the pipe schedule (or pressure class for socket-weld/threaded tees).\n"
    "Select the run size from the upper list, then select the branch size from the 'Branch size' list.\n"
    "For butt-weld tees, both lists show nominal diameter, outer diameter, and wall thickness.\n"
    "For socket-weld or threaded tees, the lists show nominal diameter and outer diameter.\n"
    "Use the 'Insert on Run' / 'Insert on Branch' radio buttons to choose which port attaches to the selected object.\n"
    "Click 'Insert' to insert the tee.\n"
    "After insertion, the rotation dial may be used to rotate the tee about the insertion port axis to the desired orientation.\n"
    "Apply button:\n"
    "Modifies the selected tee(s) to apply the selected schedule, run size, and branch size.\n"
    "\n"
    "Reverse button:\n"
    "Rotates the tee 180 degrees about its attachment port.\n"
    "\n"
)

gasket_tooltip = (
    "Tool to insert a spiral-wound gasket and/or stud bolt set at a flanged joint\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select an object to position the gasket or bolts \n"
    " • If a ported object (such as a flange) is selected, the gasket/bolts will snap to the nearest port. \n"
    " • If a circular edge is selected, the gasket/bolts will be inserted centered on that edge. \n"
    " • If a vertex is selected, the gasket/bolts will be inserted at that point. \n"
    " • If no objects are selected, the gasket/bolts will be inserted at the origin. \n"
    "\n"
    "In the window, select the flange pressure class (e.g. 150lb, 300lb) from the rating list, then select the nominal diameter from the size list.\n"
    "Use the check boxes to select what to insert:\n"
    " • 'Insert Gasket' (checked by default): inserts a spiral-wound gasket object.\n"
    " • 'Insert Bolts': inserts a stud bolt and nut set object. Bolt dimensions are read from the matching Bolt_<rating>.csv file for the selected pressure class and size.\n"
    "At least one check box must be checked. Both may be checked to insert the gasket and bolt set together at the same location.\n"
    "Click 'Insert' to insert the selected objects.\n"
    "Apply button:\n"
    "Modifies the selected gasket(s) to apply the selected pressure class and nominal diameter.\n"
    "\n"
    "Reverse button:\n"
    "Rotates the gasket/bolts 180 degrees about its attachment port.\n"
    "\n"
)

flange_tooltip = (
    "Tool to insert a pipe flange\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select an object to attach the flange to that object \n"
    " • If the selected object has ports, it will insert the flange at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the flange at the highest numbered port. \n"
    " • If the selected object has no ports, the flange will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the flange if it is inserted backwards. \n"
    " • If no objects are selected, the flange will be inserted at the origin aligned with the Z axis \n"
    "\n"
    "In the window, select the flange standard and pressure class from the rating list, then select the nominal diameter from the size list.\n"
    "Use the 'Connect on Weld End' / 'Connect on Flange Face' radio buttons to choose which end attaches to the selected port.\n"
    "For weld-neck (WN) flanges, a 'Pipe Schedule' list is shown to select the pipe schedule used to calculate the bore diameter.\n"
    "If attaching a flange to pipe, the 'Remove pipe equivalent length' check box may be checked to shorten the pipe length such that the inserted flange's face is at the original end of pipe position.\n"
    "Click 'Insert' to insert the flange.\n"
    "Apply button:\n"
    "Modifies the selected flange(s) to apply the selected standard, pressure class, and nominal diameter.\n"
    "\n"
    "Reverse button:\n"
    "Rotates the flange 180 degrees about its attachment port.\n"
    "\n"
)

ubolt_tooltip = (
    "Tool to insert pipe clamps\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select a pipe object to attach U-bolts along it \n"
    " • If a pipe object is selected, the U-bolt size is automatically matched to the pipe's nominal diameter. U-bolts may be inserted at the head (near Port 0), middle, and/or tail (near Port 1) of the pipe using the check boxes. \n"
    " • If no objects are selected, a single clamp will be inserted at the origin. \n"
    " • Beam clamp rows are inserted as standalone beam clamps. If a face or object is selected, the beam clamp is placed at that selection. \n"
    "\n"
    "In the window, select the clamp standard from the rating list, then select the size from the size list.\n"
    "Use the check boxes to select the insertion positions along the pipe:\n"
    " • Head: inserts a U-bolt offset from Port 0 by half the U-bolt width (C dimension).\n"
    " • Middle: inserts a U-bolt at the midpoint of the pipe.\n"
    " • Tail: inserts a U-bolt offset from Port 1 by half the U-bolt width (C dimension).\n"
    "Use the 'Ref. face' button to select a flat reference face that controls the rotational orientation of the U-bolt saddle.\n"
    "Click 'Insert' to insert the U-bolt(s).\n"
    "\n"
)

coupling_union_tooltip = (
    "Tool to insert a socket-weld or threaded coupling or union fitting\n"
    "______________________________________________________________________________________________________________________________________ \n"
    "Usage \n"
    "Select an object to attach the fitting to that object \n"
    " • If the selected object has ports, it will insert the fitting at the nearest port to the selected edge, face, or vertex. If the entire object is selected, it will insert the fitting at the highest numbered port. \n"
    " • If the selected object has no ports, the fitting will be inserted perpendicular to the selected edge or face. The 'Reverse' button can be used to reverse the fitting if it is inserted backwards. \n"
    " • If no objects are selected, the fitting will be inserted at the origin aligned with the Z axis \n"
    "\n"
    "Use the 'Coupling' / 'Union' radio buttons at the top of the window to switch between fitting types.\n"
    "\n"
    "Coupling mode:\n"
    "Select the pressure class from the rating list. Select the Port 0 nominal diameter from the upper list, then select the Port 1 nominal diameter from the 'Port 1 size' list. Reduced-bore couplings are available where both ends differ in size.\n"
    "\n"
    "Union mode:\n"
    "Select the pressure class from the rating list, then select the nominal diameter from the size list. Unions are always equal-bore.\n"
    "\n"
    "Click 'Insert' to insert the fitting.\n"
    "Apply button:\n"
    "Modifies the selected coupling or union object(s) to apply the selected pressure class and nominal diameter(s).\n"
    "\n"
    "Reverse button:\n"
    "Rotates the fitting 180 degrees about its base pivot point.\n"
    "\n"
)
